// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by listRenderables.js

// Imports will be auto-generated by the script

export default class ListRenderables {
  static getRenderable(name: string) {
    // Map of renderables will be auto-generated
    return null;
  }
  
  static getRenderableNames(): string[] {
    return [
      // List of renderable names will be auto-generated
    ];
  }
}
