// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by listRenderables.js through the npm run list:renderables command

import ApiBelongsToManyTestRenderable from './services/crud/api/ApiBelongsToManyTestRenderable';
import ApiCollectionRenderable from './services/crud/api/ApiCollectionRenderable';
import ApiHasManyTestRenderable from './services/crud/api/ApiHasManyTestRenderable';
import ApiResourceRenderable from './services/crud/api/ApiResourceRenderable';
import ApiStoreRequestRenderable from './services/crud/api/ApiStoreRequestRenderable';
import ApiTestRenderable from './services/crud/api/ApiTestRenderable';
import ApiUpdateRequestRenderable from './services/crud/api/ApiUpdateRequestRenderable';
import ApiAuthControllerRenderable from './services/crud/controllers/ApiAuthControllerRenderable';
import ApiBelongsToManyControllerRenderable from './services/crud/controllers/ApiBelongsToManyControllerRenderable';
import ApiControllerRenderable from './services/crud/controllers/ApiControllerRenderable';
import ApiHasManyControllerRenderable from './services/crud/controllers/ApiHasManyControllerRenderable';
import FilamentBelongsToManyRelationManagerRenderable from './services/crud/views/filament/FilamentBelongsToManyRelationManagerRenderable';
import FilamentCreateComponentRenderable from './services/crud/views/filament/FilamentCreateComponentRenderable';
import FilamentEditComponentRenderable from './services/crud/views/filament/FilamentEditComponentRenderable';
import FilamentListComponentRenderable from './services/crud/views/filament/FilamentListComponentRenderable';
import FilamentResourceRenderable from './services/crud/views/filament/FilamentResourceRenderable';
import FilamentViewComponentRenderable from './services/crud/views/filament/FilamentViewComponentRenderable';
import LivewireCreateComponentRenderable from './services/crud/views/livewire/LivewireCreateComponentRenderable';
import LivewireCreateDetailFormComponentRenderable from './services/crud/views/livewire/LivewireCreateDetailFormComponentRenderable';
import LivewireCreateFormComponentRenderable from './services/crud/views/livewire/LivewireCreateFormComponentRenderable';
import LivewireCreateViewRenderable from './services/crud/views/livewire/LivewireCreateViewRenderable';
import LivewireEditComponentRenderable from './services/crud/views/livewire/LivewireEditComponentRenderable';
import LivewireEditViewRenderable from './services/crud/views/livewire/LivewireEditViewRenderable';
import LivewireHasManyDetailComponentRenderable from './services/crud/views/livewire/LivewireHasManyDetailComponentRenderable';
import LivewireHasManyDetailViewRenderable from './services/crud/views/livewire/LivewireHasManyDetailViewRenderable';
import LivewireIndexComponentRenderable from './services/crud/views/livewire/LivewireIndexComponentRenderable';
import LivewireIndexViewRenderable from './services/crud/views/livewire/LivewireIndexViewRenderable';
import LivewireUpdateDetailFormComponentRenderable from './services/crud/views/livewire/LivewireUpdateDetailFormComponentRenderable';
import LivewireUpdateFormComponentRenderable from './services/crud/views/livewire/LivewireUpdateFormComponentRenderable';
import NovaResourceRenderable from './services/crud/views/nova/NovaResourceRenderable';
import DatabaseSeederRenderable from './services/database/DatabaseSeederRenderable';
import AppMenuRenderable from './services/menu/AppMenuRenderable';
import AppResponsiveMenuRenderable from './services/menu/AppResponsiveMenuRenderable';
import BreezeNavigationRenderable from './services/menu/BreezeNavigationRenderable';
import FactoryRenderable from './services/model/FactoryRenderable';
import ModelRenderable from './services/model/ModelRenderable';
import PolicyRenderable from './services/model/PolicyRenderable';
import SeederRenderable from './services/model/SeederRenderable';
import PageComponentRenderable from './services/page/PageComponentRenderable';
import PageViewRenderable from './services/page/PageViewRenderable';
import ApiRoutesRenderable from './services/routes/ApiRoutesRenderable';
import BootstrapAppRenderable from './services/routes/BootstrapAppRenderable';
import Routes from './services/routes/Routes';
import PreviewRenderable from './services/theme/PreviewRenderable';

export default class ListRenderables {
  static getRenderable(name: string) {
    
  const renderables = {
    'crud/api/ApiBelongsToManyTestRenderable': ApiBelongsToManyTestRenderable,
    'crud/api/ApiCollectionRenderable': ApiCollectionRenderable,
    'crud/api/ApiHasManyTestRenderable': ApiHasManyTestRenderable,
    'crud/api/ApiResourceRenderable': ApiResourceRenderable,
    'crud/api/ApiStoreRequestRenderable': ApiStoreRequestRenderable,
    'crud/api/ApiTestRenderable': ApiTestRenderable,
    'crud/api/ApiUpdateRequestRenderable': ApiUpdateRequestRenderable,
    'crud/controllers/ApiAuthControllerRenderable': ApiAuthControllerRenderable,
    'crud/controllers/ApiBelongsToManyControllerRenderable': ApiBelongsToManyControllerRenderable,
    'crud/controllers/ApiControllerRenderable': ApiControllerRenderable,
    'crud/controllers/ApiHasManyControllerRenderable': ApiHasManyControllerRenderable,
    'crud/views/filament/FilamentBelongsToManyRelationManagerRenderable': FilamentBelongsToManyRelationManagerRenderable,
    'crud/views/filament/FilamentCreateComponentRenderable': FilamentCreateComponentRenderable,
    'crud/views/filament/FilamentEditComponentRenderable': FilamentEditComponentRenderable,
    'crud/views/filament/FilamentListComponentRenderable': FilamentListComponentRenderable,
    'crud/views/filament/FilamentResourceRenderable': FilamentResourceRenderable,
    'crud/views/filament/FilamentViewComponentRenderable': FilamentViewComponentRenderable,
    'crud/views/livewire/LivewireCreateComponentRenderable': LivewireCreateComponentRenderable,
    'crud/views/livewire/LivewireCreateDetailFormComponentRenderable': LivewireCreateDetailFormComponentRenderable,
    'crud/views/livewire/LivewireCreateFormComponentRenderable': LivewireCreateFormComponentRenderable,
    'crud/views/livewire/LivewireCreateViewRenderable': LivewireCreateViewRenderable,
    'crud/views/livewire/LivewireEditComponentRenderable': LivewireEditComponentRenderable,
    'crud/views/livewire/LivewireEditViewRenderable': LivewireEditViewRenderable,
    'crud/views/livewire/LivewireHasManyDetailComponentRenderable': LivewireHasManyDetailComponentRenderable,
    'crud/views/livewire/LivewireHasManyDetailViewRenderable': LivewireHasManyDetailViewRenderable,
    'crud/views/livewire/LivewireIndexComponentRenderable': LivewireIndexComponentRenderable,
    'crud/views/livewire/LivewireIndexViewRenderable': LivewireIndexViewRenderable,
    'crud/views/livewire/LivewireUpdateDetailFormComponentRenderable': LivewireUpdateDetailFormComponentRenderable,
    'crud/views/livewire/LivewireUpdateFormComponentRenderable': LivewireUpdateFormComponentRenderable,
    'crud/views/nova/NovaResourceRenderable': NovaResourceRenderable,
    'database/DatabaseSeederRenderable': DatabaseSeederRenderable,
    'menu/AppMenuRenderable': AppMenuRenderable,
    'menu/AppResponsiveMenuRenderable': AppResponsiveMenuRenderable,
    'menu/BreezeNavigationRenderable': BreezeNavigationRenderable,
    'model/FactoryRenderable': FactoryRenderable,
    'model/ModelRenderable': ModelRenderable,
    'model/PolicyRenderable': PolicyRenderable,
    'model/SeederRenderable': SeederRenderable,
    'page/PageComponentRenderable': PageComponentRenderable,
    'page/PageViewRenderable': PageViewRenderable,
    'routes/ApiRoutesRenderable': ApiRoutesRenderable,
    'routes/BootstrapAppRenderable': BootstrapAppRenderable,
    'routes/Routes': Routes,
    'theme/PreviewRenderable': PreviewRenderable
  };
  
    
    return renderables[name] || null;
  }
  
  static getRenderableNames(): string[] {
    return [
      'crud/api/ApiBelongsToManyTestRenderable',
      'crud/api/ApiCollectionRenderable',
      'crud/api/ApiHasManyTestRenderable',
      'crud/api/ApiResourceRenderable',
      'crud/api/ApiStoreRequestRenderable',
      'crud/api/ApiTestRenderable',
      'crud/api/ApiUpdateRequestRenderable',
      'crud/controllers/ApiAuthControllerRenderable',
      'crud/controllers/ApiBelongsToManyControllerRenderable',
      'crud/controllers/ApiControllerRenderable',
      'crud/controllers/ApiHasManyControllerRenderable',
      'crud/views/filament/FilamentBelongsToManyRelationManagerRenderable',
      'crud/views/filament/FilamentCreateComponentRenderable',
      'crud/views/filament/FilamentEditComponentRenderable',
      'crud/views/filament/FilamentListComponentRenderable',
      'crud/views/filament/FilamentResourceRenderable',
      'crud/views/filament/FilamentViewComponentRenderable',
      'crud/views/livewire/LivewireCreateComponentRenderable',
      'crud/views/livewire/LivewireCreateDetailFormComponentRenderable',
      'crud/views/livewire/LivewireCreateFormComponentRenderable',
      'crud/views/livewire/LivewireCreateViewRenderable',
      'crud/views/livewire/LivewireEditComponentRenderable',
      'crud/views/livewire/LivewireEditViewRenderable',
      'crud/views/livewire/LivewireHasManyDetailComponentRenderable',
      'crud/views/livewire/LivewireHasManyDetailViewRenderable',
      'crud/views/livewire/LivewireIndexComponentRenderable',
      'crud/views/livewire/LivewireIndexViewRenderable',
      'crud/views/livewire/LivewireUpdateDetailFormComponentRenderable',
      'crud/views/livewire/LivewireUpdateFormComponentRenderable',
      'crud/views/nova/NovaResourceRenderable',
      'database/DatabaseSeederRenderable',
      'menu/AppMenuRenderable',
      'menu/AppResponsiveMenuRenderable',
      'menu/BreezeNavigationRenderable',
      'model/FactoryRenderable',
      'model/ModelRenderable',
      'model/PolicyRenderable',
      'model/SeederRenderable',
      'page/PageComponentRenderable',
      'page/PageViewRenderable',
      'routes/ApiRoutesRenderable',
      'routes/BootstrapAppRenderable',
      'routes/Routes',
      'theme/PreviewRenderable'
    ];
  }
}
