export default {
    cdn: "https://cdn.jsdelivr.net/npm/foundation-sites@6.8.1/dist/css/foundation.min.css",
    keys: {
        "default.delay": "fade-in",
        "table": "table-scroll",
        "table.container": "overflow-hidden rounded",
        "table.head": "background-gray",
        "table.head.row": "text-gray",
        "table.head.col": "small-padding-left small-padding-right padding-vertical-1 text-uppercase",
        "table.body": "background-white",
        "table.body.row": "text-dark",
        "table.body.col": "small-padding-left small-padding-right padding-vertical-2",
        "ui.button": "button primary",
        "ui.input": "input-group", 
        "ui.input.checkbox": "",
        "ui.label": "label",
        "ui.input.error": "input-invalid", 
        "ui.breadcrumbs.container": "grid-x align-spaced py-1", 
        "ui.breadcrumbs.list": "breadcrumbs", 
        "ui.breadcrumbs.list.item": "",
        "ui.breadcrumbs.list.item.link": "breadcrumb-link",
        "ui.breadcrumbs.separator": "show-for-sr",
        "crud.index.container": "grid-container",
        "crud.table.head.col.extra": "cursor-pointer",
        "crud.table.head.action-col": "small-padding-left small-padding-right padding-vertical-1 text-right text-uppercase",
        "crud.table.body.col.extra": "truncate",
        "crud.table.body.action-col": "small-padding-left small-padding-right padding-vertical-2 text-right",
        "crud.action-link": "text-primary hover:underline cursor-pointer",
        "crud.action-link-danger": "text-alert hover:underline cursor-pointer",
        "crud.index.tools": "grid-x align-top py-4",
        "crud.pagination.container": "pagination-centered", 
        "crud.container": "grid-container",
        "crud.header": "w-100 text-gray font-bold padding-vertical-2 text-uppercase",
        "crud.form": "w-100",
        "crud.form.container": "overflow-hidden rounded background-white",
        "crud.form.inputs.container": "padding-2",
        "crud.form.input.group": "w-100",
        "crud.form.input.extra": "w-100",
        "crud.form.input.image": "thumbnail", 
        "crud.form.input.image.button": "button tiny",
        "crud.form.buttons-container": "grid-x align-spaced padding-2",
    },
}
